Kens tube likelihood algorithm is slow in both R and Python. Can I make it go any faster?

In [1]:
import pandas
import scipy.misc

In [2]:
data = pandas.read_csv('dump_Mm_purkinje.txt', sep='\t', header=0)

In [3]:
data.columns

Index(['cell_type', 'run', 'gene_id', 'concentration', 'fpkm', 'success'], dtype='object')

In [4]:
data

cell_type     run              gene_id  concentration    fpkm  success
0     Mm_purkinje  p15288  gSpikein_ERCC-00002       1806.000  486.37        1
1     Mm_purkinje  p15288  gSpikein_ERCC-00003        112.875   57.94        1
2     Mm_purkinje  p15288  gSpikein_ERCC-00004        903.000  343.27        1
3     Mm_purkinje  p15288  gSpikein_ERCC-00009        112.875   17.44        1
4     Mm_purkinje  p15288  gSpikein_ERCC-00012          0.014    0.00        0
5     Mm_purkinje  p15288  gSpikein_ERCC-00013          0.110    0.00        0
6     Mm_purkinje  p15288  gSpikein_ERCC-00014          0.441    0.00        0
7     Mm_purkinje  p15288  gSpikein_ERCC-00016          0.028    0.00        0
8     Mm_purkinje  p15288  gSpikein_ERCC-00017          0.014    0.00        0
9     Mm_purkinje  p15288  gSpikein_ERCC-00019          3.527    0.00        0
10    Mm_purkinje  p15288  gSpikein_ERCC-00022         28.219    0.19        1
11    Mm_purkinje  p15288  gSpikein_ERCC-00024          0.028    0.00        0
12    Mm_purkinje  p15288  gSpikein_ERCC-00025          7.055    0.00        0
13    Mm_purkinje  p15288  gSpikein_ERCC-00028          0.441    0.85        1
14    Mm_purkinje  p15288  gSpikein_ERCC-00031          0.220    0.00        0
15    Mm_purkinje  p15288  gSpikein_ERCC-00033          0.220    0.00        0
16    Mm_purkinje  p15288  gSpikein_ERCC-00034          0.882    0.00        0
17    Mm_purkinje  p15288  gSpikein_ERCC-00035         14.109    0.00        0
18    Mm_purkinje  p15288  gSpikein_ERCC-00039          0.441    0.00        0
19    Mm_purkinje  p15288  gSpikein_ERCC-00040          0.110    0.00        0
20    Mm_purkinje  p15288  gSpikein_ERCC-00041          0.028    0.00        0
21    Mm_purkinje  p15288  gSpikein_ERCC-00042         56.438   17.25        1
22    Mm_purkinje  p15288  gSpikein_ERCC-00043         56.438   26.68        1
23    Mm_purkinje  p15288  gSpikein_ERCC-00044         14.109    0.12        1
24    Mm_purkinje  p15288  gSpikein_ERCC-00046        451.500  231.35        1
25    Mm_purkinje  p15288  gSpikein_ERCC-00048          0.002    0.00        0
26    Mm_purkinje  p15288  gSpikein_ERCC-00051          7.055    0.00        0
27    Mm_purkinje  p15288  gSpikein_ERCC-00053          3.527    0.00        0
28    Mm_purkinje  p15288  gSpikein_ERCC-00054          1.764    0.00        0
29    Mm_purkinje  p15288  gSpikein_ERCC-00057          0.002    0.00        0
...           ...     ...                  ...            ...     ...      ...
2914  Mm_purkinje  s15271  gSpikein_ERCC-00116         56.438    2.87        1
2915  Mm_purkinje  s15271  gSpikein_ERCC-00117          0.007    0.00        0
2916  Mm_purkinje  s15271  gSpikein_ERCC-00120          0.110    0.00        0
2917  Mm_purkinje  s15271  gSpikein_ERCC-00123          0.028    0.00        0
2918  Mm_purkinje  s15271  gSpikein_ERCC-00126          1.764    0.00        0
2919  Mm_purkinje  s15271  gSpikein_ERCC-00130       3612.000  562.99        1
2920  Mm_purkinje  s15271  gSpikein_ERCC-00131         14.109    3.13        1
2921  Mm_purkinje  s15271  gSpikein_ERCC-00134          0.220    0.00        0
2922  Mm_purkinje  s15271  gSpikein_ERCC-00136        225.750   50.96        1
2923  Mm_purkinje  s15271  gSpikein_ERCC-00137          0.110    0.00        0
2924  Mm_purkinje  s15271  gSpikein_ERCC-00138          0.014    0.00        0
2925  Mm_purkinje  s15271  gSpikein_ERCC-00142          0.028    0.00        0
2926  Mm_purkinje  s15271  gSpikein_ERCC-00143          0.441    8.48        1
2927  Mm_purkinje  s15271  gSpikein_ERCC-00144          3.527    0.00        0
2928  Mm_purkinje  s15271  gSpikein_ERCC-00145        112.875    7.73        1
2929  Mm_purkinje  s15271  gSpikein_ERCC-00147          0.110    0.00        0
2930  Mm_purkinje  s15271  gSpikein_ERCC-00148          1.764    1.25        1
2931  Mm_purkinje  s15271  gSpikein_ERCC-00150          0.441    0.00        0
2932  Mm_purkinje  s15271  gSpikein_ERCC-00154          0.

In [15]:
def prob_py(series, p):
    return series.success * series.concentration


In [18]:
data.apply(prob_py, axis=1, args=(1,))

0       1806.000
1        112.875
2        903.000
3        112.875
4          0.000
5          0.000
6          0.000
7          0.000
8          0.000
9          0.000
10        28.219
11         0.000
12         0.000
13         0.441
14         0.000
15         0.000
16         0.000
17         0.000
18         0.000
19         0.000
20         0.000
21        56.438
22        56.438
23        14.109
24       451.500
25         0.000
26         0.000
27         0.000
28         0.000
29         0.000
          ...   
2914      56.438
2915       0.000
2916       0.000
2917       0.000
2918       0.000
2919    3612.000
2920      14.109
2921       0.000
2922     225.750
2923       0.000
2924       0.000
2925       0.000
2926       0.441
2927       0.000
2928     112.875
2929       0.000
2930       1.764
2931       0.000
2932       0.000
2933       0.000
2934       0.000
2935       0.000
2936       0.882
2937       7.055
2938       0.000
2939       0.000
2940       0.000
2941       0.0

In [6]:
result = data.apply(prob_py, axis=1)
result.index = data.index
result

0       1806.000
1        112.875
2        903.000
3        112.875
4          0.000
5          0.000
6          0.000
7          0.000
8          0.000
9          0.000
10        28.219
11         0.000
12         0.000
13         0.441
14         0.000
15         0.000
16         0.000
17         0.000
18         0.000
19         0.000
20         0.000
21        56.438
22        56.438
23        14.109
24       451.500
25         0.000
26         0.000
27         0.000
28         0.000
29         0.000
          ...   
2914      56.438
2915       0.000
2916       0.000
2917       0.000
2918       0.000
2919    3612.000
2920      14.109
2921       0.000
2922     225.750
2923       0.000
2924       0.000
2925       0.000
2926       0.441
2927       0.000
2928     112.875
2929       0.000
2930       1.764
2931       0.000
2932       0.000
2933       0.000
2934       0.000
2935       0.000
2936       0.882
2937       7.055
2938       0.000
2939       0.000
2940       0.000
2941       0.0

In [7]:
result[data.run == 'p15288'].sum()

11863.782999999999

In [8]:
result[data.run != 'p15288'].sum()

371458.77800000005

In [9]:
import numpy

In [10]:
k = numpy.arange(0, 61)

In [11]:
(1-0.1) ** numpy.arange(0, 61)

array([ 1.        ,  0.9       ,  0.81      ,  0.729     ,  0.6561    ,
        0.59049   ,  0.531441  ,  0.4782969 ,  0.43046721,  0.38742049,
        0.34867844,  0.3138106 ,  0.28242954,  0.25418658,  0.22876792,
        0.20589113,  0.18530202,  0.16677182,  0.15009464,  0.13508517,
        0.12157665,  0.10941899,  0.09847709,  0.08862938,  0.07976644,
        0.0717898 ,  0.06461082,  0.05814974,  0.05233476,  0.04710129,
        0.04239116,  0.03815204,  0.03433684,  0.03090315,  0.02781284,
        0.02503156,  0.0225284 ,  0.02027556,  0.018248  ,  0.0164232 ,
        0.01478088,  0.01330279,  0.01197252,  0.01077526,  0.00969774,
        0.00872796,  0.00785517,  0.00706965,  0.00636269,  0.00572642,
        0.00515378,  0.0046384 ,  0.00417456,  0.0037571 ,  0.00338139,
        0.00304325,  0.00273893,  0.00246503,  0.00221853,  0.00199668,
        0.00179701])

In [12]:
.05 ** k * 2.71 ** -0.05/scipy.misc.factorial(k)

array([  9.51374563e-001,   4.75687281e-002,   1.18921820e-003,
         1.98203034e-005,   2.47753792e-007,   2.47753792e-009,
         2.06461494e-011,   1.47472496e-013,   9.21703097e-016,
         5.12057276e-018,   2.56028638e-020,   1.16376654e-022,
         4.84902724e-025,   1.86501048e-027,   6.66075170e-030,
         2.22025057e-032,   6.93828302e-035,   2.04067148e-037,
         5.66853188e-040,   1.49171892e-042,   3.72929729e-045,
         8.87927926e-048,   2.01801801e-050,   4.38699568e-053,
         9.13957433e-056,   1.82791487e-058,   3.51522090e-061,
         6.50966833e-064,   1.16244077e-066,   2.00420823e-069,
         3.34034705e-072,   5.38765653e-075,   8.41821333e-078,
         1.27548687e-080,   1.87571598e-083,   2.67959426e-086,
         3.72165869e-089,   5.02926851e-092,   6.61745856e-095,
         8.48392123e-098,   1.06049015e-100,   1.29328068e-103,
         1.53961985e-106,   1.79025564e-109,   2.03438141e-112,
         2.26042379e-115,   2.45698238e-

In [13]:
import scipy.misc

In [14]:
scipy.misc.factorial(k)

array([  1.00000000e+00,   1.00000000e+00,   2.00000000e+00,
         6.00000000e+00,   2.40000000e+01,   1.20000000e+02,
         7.20000000e+02,   5.04000000e+03,   4.03200000e+04,
         3.62880000e+05,   3.62880000e+06,   3.99168000e+07,
         4.79001600e+08,   6.22702080e+09,   8.71782912e+10,
         1.30767437e+12,   2.09227899e+13,   3.55687428e+14,
         6.40237371e+15,   1.21645100e+17,   2.43290201e+18,
         5.10909422e+19,   1.12400073e+21,   2.58520167e+22,
         6.20448402e+23,   1.55112100e+25,   4.03291461e+26,
         1.08888695e+28,   3.04888345e+29,   8.84176199e+30,
         2.65252860e+32,   8.22283865e+33,   2.63130837e+35,
         8.68331762e+36,   2.95232799e+38,   1.03331480e+40,
         3.71993327e+41,   1.37637531e+43,   5.23022617e+44,
         2.03978821e+46,   8.15915283e+47,   3.34525266e+49,
         1.40500612e+51,   6.04152631e+52,   2.65827157e+54,
         1.19622221e+56,   5.50262216e+57,   2.58623242e+59,
         1.24139156e+61,

In [19]:
data.columns

Index(['cell_type', 'run', 'gene_id', 'concentration', 'fpkm', 'success'], dtype='object')

In [20]:
data.sort_values(by='concentration', ascending=False)

cell_type     run              gene_id  concentration     fpkm  \
1539  Mm_purkinje  s15256  gSpikein_ERCC-00130       3612.000   403.79   
1907  Mm_purkinje  s15260  gSpikein_ERCC-00130       3612.000   939.91   
2367  Mm_purkinje  s15265  gSpikein_ERCC-00130       3612.000   577.85   
619   Mm_purkinje  p15294  gSpikein_ERCC-00130       3612.000   560.99   
2275  Mm_purkinje  s15264  gSpikein_ERCC-00130       3612.000   457.48   
2183  Mm_purkinje  s15263  gSpikein_ERCC-00130       3612.000   640.26   
2091  Mm_purkinje  s15262  gSpikein_ERCC-00130       3612.000   535.07   
803   Mm_purkinje  p15296  gSpikein_ERCC-00130       3612.000   739.73   
1999  Mm_purkinje  s15261  gSpikein_ERCC-00130       3612.000   582.72   
895   Mm_purkinje  p15297  gSpikein_ERCC-00130       3612.000   915.38   
1815  Mm_purkinje  s15259  gSpikein_ERCC-00130       3612.000   824.99   
2459  Mm_purkinje  s15266  gSpikein_ERCC-00130       3612.000   401.11   
987   Mm_purkinje  p15298  gSpikein_ERCC-00130       3612.000   626.23   
1723  Mm_purkinje  s15258  gSpikein_ERCC-00130       3612.000  1108.31   
1079  Mm_purkinje  p15299  gSpikein_ERCC-00130       3612.000   764.99   
1631  Mm_purkinje  s15257  gSpikein_ERCC-00130       3612.000   934.64   
1171  Mm_purkinje  p15300  gSpikein_ERCC-00130       3612.000   744.08   
1447  Mm_purkinje  p15303  gSpikein_ERCC-00130       3612.000   503.93   
1263  Mm_purkinje  p15301  gSpikein_ERCC-00130       3612.000   684.44   
67    Mm_purkinje  p15288  gSpikein_ERCC-00130       3612.000   720.18   
527   Mm_purkinje  p15293  gSpikein_ERCC-00130       3612.000   667.63   
711   Mm_purkinje  p15295  gSpikein_ERCC-00130       3612.000   644.52   
1355  Mm_purkinje  p15302  gSpikein_ERCC-00130       3612.000   779.29   
2551  Mm_purkinje  s15267  gSpikein_ERCC-00130       3612.000   633.73   
251   Mm_purkinje  p15290  gSpikein_ERCC-00130       3612.000   733.90   
343   Mm_purkinje  p15291  gSpikein_ERCC-00130       3612.000   783.09   
2643  Mm_purkinje  s15268  gSpikein_ERCC-00130       3612.000   574.04   
2827  Mm_purkinje  s15270  gSpikein_ERCC-00130       3612.000   653.09   
2735  Mm_purkinje  s15269  gSpikein_ERCC-00130       3612.000   384.67   
159   Mm_purkinje  p15289  gSpikein_ERCC-00130       3612.000   616.47   
...           ...     ...                  ...            ...      ...   
853   Mm_purkinje  p15297  gSpikein_ERCC-00048          0.002     0.00   
2785  Mm_purkinje  s15270  gSpikein_ERCC-00048          0.002     0.00   
2789  Mm_purkinje  s15270  gSpikein_ERCC-00057          0.002     0.00   
485   Mm_purkinje  p15293  gSpikein_ERCC-00048          0.002     0.00   
2800  Mm_purkinje  s15270  gSpikein_ERCC-00075          0.002     0.00   
776   Mm_purkinje  p15296  gSpikein_ERCC-00075          0.002     0.00   
765   Mm_purkinje  p15296  gSpikein_ERCC-00057          0.002     0.00   
761   Mm_purkinje  p15296  gSpikein_ERCC-00048          0.002     0.00   
1052  Mm_purkinje  p15299  gSpikein_ERCC-00075          0.002     0.00   
2616  Mm_purkinje  s15268  gSpikein_ERCC-00075          0.002     0.00   
2605  Mm_purkinje  s15268  gSpikein_ERCC-00057          0.002     0.00   
2601  Mm_purkinje  s15268  gSpikein_ERCC-00048          0.002     0.00   
209   Mm_purkinje  p15290  gSpikein_ERCC-00048          0.002     0.00   
393   Mm_purkinje  p15292  gSpikein_ERCC-00048          0.002     0.00   
1328  Mm_purkinje  p15302  gSpikein_ERCC-00075          0.002     0.00   
1317  Mm_purkinje  p15302  gSpikein_ERCC-00057          0.002     0.00   
1313  Mm_purkinje  p15302  gSpikein_ERCC-00048          0.002     0.00   
40    Mm_purkinje  p15288  gSpikein_ERCC-00075          0.002     0.00   
2509  Mm_purkinje  s15267  gSpikein_ERCC-00048          0.002     0.00   
2513  Mm_purkinje  s15267  gSpikein_ERCC-00057          0.002     0.00   
2524  Mm_purkinje  s15267  gSpikein_ERCC-00075          0.002     0.00   
1236  Mm_purkinje  p15301  gSpikein_ERCC-00075          0.002     0.00   
1225  Mm_pur

In [21]:
data.max?

In [26]:
data.concentration.max()

3612.0

In [25]:
data.iloc[67]

cell_type                Mm_purkinje
run                           p15288
gene_id          gSpikein_ERCC-00130
concentration                   3612
fpkm                          720.18
success                            1
Name: 67, dtype: object